# Generated by Django 5.0.9 on 2026-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productsafetycache',
            index=models.Index(fields=['category', 'product_id'], name='product_saf_categor_efff75_idx'),
        ),
    ]
